# Example Buildkite pipeline
steps:
  - label: ":rocket: Deploy to production"
    command: "./scripts/deploy.sh --env=production"
    branches: "main"
    agents:
      queue: "deploy"
      os: "linux"
    
  - label: ":hammer: Run tests"
    command: "./.buildkite/scripts/run-tests.sh"
    plugins:
      - docker#v3.7.0:
          image: "node:14"
          workdir: "/app"

  - wait: ~
  
  - block: ":lock: Require approval"
    prompt: "Deploy to production?"
    
  - label: ":shipit: Notify team"
    command: "./scripts/notify.sh"
    
# Environment variables
env:
  DEPLOY_ENV: "production"
  LOG_LEVEL: "info"

agents:
  queue: "default"
  os: "linux"